name: "Dev Release: Build and Push Docker Image to DockerHub"

on:
  push:
    branches:
      - "dev"

jobs:
  build-and-push-dev-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push offat-base docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          file: ./src/DockerFiles/base-Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat-base:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and push offat docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          file: ./src/DockerFiles/dev/cli-Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and push offat-api docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          file: ./src/DockerFiles/dev/backend-api-Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat-api:dev
          platforms: linux/amd64,linux/arm64
      - name: Build and push offat-api-worker docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/
          file: ./src/DockerFiles/dev/backend-api-worker-Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat-api-worker:dev
          platforms: linux/amd64,linux/arm64
