# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload OWASP OFFAT Python Package to PyPi

on:
    release:
        types: [published]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.x"
            - name: change cwd to src directory
              run: cd src
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: |
                  cd src
                  python -m build
            - name: Publish package
              uses: pypa/gh-action-pypi-publish@v1.8.10
              with:
                  packages-dir: src/dist
